### ISSUE TITLE
Can't compile successfully when upgrate to Neo4j 2.2.5

### ISSUE THREAD

**Issue by xinsong001** [neo4j-contrib/spatial#196]
Following the error:

[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/Git_Local_Repo/spatial/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[35,8] org.neo4j.gis.sp
atial.indexprovider.SpatialIndexImplementation is not abstract and does not override abstract method shutdown() in org.neo4j.graphdb.index.IndexImplementation
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Thanks all for your contributions very much:)

**Comment by amorgner** [comment]
Which branch are you trying to compile?

For 2.2.5, you can use the 0.14-neo4j-2.2 branch which should compile with 2.2.5: https://github.com/neo4j-contrib/spatial/tree/0.14-neo4j-2.2

**Comment by xinsong001** [comment]
Oh, It's my fault. 

I try to use the master branch and modify the POM file, change the neo4j 2.2.3 verion to 2.2.5, then compile 0.15-neo4j-2.2.5 :)

Because I used 0.15-neo4j-2.2.3 before. But I could not download Neo4j 2.2.3 from offical web site now, I have to upgarde to Neo4j 2.2.5, then need to compile corresponding Server Spatial Plugin too. 

Indeed, I know little about the difference between 0.14 and 0.15.   

Thanks very much.

Regards

Xinsong
  



xsxia001@sohu.com
 
From: Axel Morgner
Date: 2015-09-28 23:49
To: neo4j-contrib/spatial
CC: xinsong001
Subject: Re: [spatial] Can't compile successfully when upgrate to Neo4j 2.2.5 (#196)
Which branch are you trying to compile?
For 2.2.5, you can use the 0.14-neo4j-2.2 branch which should compile with 2.2.5: https://github.com/neo4j-contrib/spatial/tree/0.14-neo4j-2.2
