### ISSUE TITLE
NoSuchMethodError in org.neo4j.graphdb.traversal.Evaluators.excludeStartPosition() in neo4j-xxx-1.8.1

### ISSUE THREAD

**Issue by bersant** [neo4j-contrib/spatial#79]
Getting following error when trying to add a Geometry to an EditableLayer in neo4j-xxx-1.8.1. Note: It works in 1.8 and below:

```
     java.lang.NoSuchMethodError: org.neo4j.graphdb.traversal.Evaluators.excludeStartPosition()Lorg/neo4j/graphdb/traversal/Evaluator;
    at org.neo4j.gis.spatial.EditableLayerImpl.addGeomNode(EditableLayerImpl.java:97)
    at org.neo4j.gis.spatial.EditableLayerImpl.add(EditableLayerImpl.java:49)
    at org.neo4j.gis.spatial.EditableLayerImpl.add(EditableLayerImpl.java:40)
```

Test Case 1: 

```
            String LAYER = "test";
    plugin.addEditableLayer(graphDb, LAYER, "WKT");
    spatialService.getOrCreateEditableLayer(LAYER);
    subLayer =  (EditableLayer) spatialService.getLayer(LAYER);
    plugin.addGeometryWKTToLayer(graphDb, "POINT(53.3  13.3)", LAYER);
```

Test  Case 2:

```
                    subLayer = spatialService.getOrCreateEditableLayer("test", "WKT");
        WKTReader wkt= new WKTReader(subLayer.getGeometryFactory());
        Geometry TestPoint = wkt.read("POINT(53.3  13.3)");
        subLayer.add(TestPoint);
```
