### ISSUE TITLE
Failed to invoke procedure spatial.withinDistance

### ISSUE THREAD

**Issue by JoranBeaufort** [neo4j-contrib/spatial#255]
Hi. I am getting following error when trying to use the withinDistance or the closest procedure:

```Failed to invoke procedure spatial.withinDistance: Caused by: java.lang.NoClassDefFoundError: org/neo4j/cypher/internal/compiler/v3_0/commands/expressions/GeographicPoint```

I create a pointlayer with:
```CALL spatial.addPointLayer('geom')```
I then create a node:
```create (n:Tile{name:'test',latitude:47.99,longitude:7.886})``` 
And finally, I add the node to the layer: 
```match (t:Tile) with t call spatial.addNode('geom',t) YIELD node return count(*)```

This all works fine! But, if I then query using: ```CALL spatial.withinDistance('geom',{latitude:47.60,longitude:7.7},100)``` I get the error above.

In addition, other queries such as ```call spatial.layers() ``` also seem to be working fine.

Ps. I am using Neo4j 3.0.2 and I downloaded and used the pre-built JAR provided for Neo4j-Spatial (v0.17 for Neo4j 3.0.2)

**Comment by craigtaverner** [comment]
Can you tell me which version of Neo4j you are using and which version of Neo4j Spatial? There was an issue in Neo4j 3.0.0 and 3.0.1 that was corrected in 3.0.2 regarding the GeographicPoint type. You are advised to use Neo4j 3.0.2, and the version of Neo4j Spatial compiled for that. See the readme at https://github.com/neo4j-contrib/spatial#using-the-neo4j-spatial-server-plugin

**Comment by JoranBeaufort** [comment]
Hi. Ill probably have time to test this today. Ill post what I find, thanks for the answer! Short side question: are there any plans for raster support in the future (e.g. a raster node type to which single rasters or raster tiles can be connected incl. bounding boxes as the spatial index)? Cheers

**Comment by craigtaverner** [comment]
Super. Looking forward to your rest results. I would test myself, but we have Swedish midsummer long weekend here :-)

Regarding rasters, there are no plans for native raster support (ie. that we can store and index rasters as native types). But I would think you could handle this easily at the application level, by storing rasters on disk, and adding only the bounding boxes (as polygons) to the Neo4j Spatial model (plus a property URI to the raster itself, if useful).

The design of Neo4j Spatial is strongly influence by the JTS library, which we use, and that is very much vector based.

**Comment by JoranBeaufort** [comment]
Just tryed again with neo4j 3.0.3 and the results are the same. I wiped the entire neo4j graph (by deleteing the graph.db folder). As you can see in the screenshot, the graph is empty and neo4j is running in version 3.0.3:

![1](https://cloud.githubusercontent.com/assets/13437059/16340350/064cd06a-3a28-11e6-9890-60e91f9586a7.png)

I again created all the rTree and connected a test node through cypher using the same steps as above:

Create pointlayer:
![2](https://cloud.githubusercontent.com/assets/13437059/16340428/740121ec-3a28-11e6-848e-9f96958d1c93.png)

Create test node:
![3](https://cloud.githubusercontent.com/assets/13437059/16340531/ed6efd74-3a28-11e6-8e1d-0849d90ca540.png)

Add node to pointlayer:
![4](https://cloud.githubusercontent.com/assets/13437059/16340459/8c3bd05e-3a28-11e6-9e6c-63e6173ead30.png)

When I try to use withinDistance, it results in the same error:
![5](https://cloud.githubusercontent.com/assets/13437059/16340484/ae64a098-3a28-11e6-86aa-d0531103b331.png)

Not quite sure what im missing at the moment...? I am using neo4j community edition and not enterprise, could this be a potential point of error?

Ps. Thanks for the answer to the raster question. I am currently looking into combining neo4j with postgres/postgis. I might write a short blog post if I find time in the next few weeks. If interested, i can let you know when and if I have written something. 

Cheers

**Comment by thiagomorato** [comment]
@JoranBeaufort did you have any luck with that?

I bumped into the same thing, version 3.0.4. I will try to compile version 3.1 to see how it goes there.

**Comment by JoranBeaufort** [comment]
@thiagomorato No, I havent gotten it to work. But I have not had time to thoroughly look at it, as I am now looking into other options. If you find a way, I'd be very interested! Its weird that it seems to be working for most people... Cheers

**Comment by craigtaverner** [comment]
I found and fixed the problem, but have not uploaded a new build because I'm working on fixing another unrelated issue. Hopefully during the weekend or next week I'll upload a new build.

The issue was that the build for 3.0.2 was in fact built against 3.0.1. My mistake. If you want a build urgently, you could rebuild yourself, otherwise wait for my build. Hopefully soon.

**Comment by JoranBeaufort** [comment]
@craigtaverner Great news, thanks for your efforts and the fast fix! :+1: 
Ill test it once you upload the new build, as it is not that urgent for me. Cheers

**Comment by thiagomorato** [comment]
It seems great, thanks for the quick reply @craigtaverner. Well I have tried to compile it by changing the pom.xml on line 4 to:

`<neo4j.version>3.0.2</neo4j.version>` 

Not sure if this is the way to do it, but I got this result which seems to be related to the original issue posted here.

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /...../spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[25,68] cannot find symbol
  symbol:   class GeographicPoint
  location: package org.neo4j.cypher.internal.compiler.v3_0.commands.expressions
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.722 s
[INFO] Finished at: 2016-07-01T17:40:39-03:00
[INFO] Final Memory: 34M/287M
[INFO] ------------------------------------------------------------------------
```

It is end of the day for me so I will see next week if you were able to upload it, if not maybe I can just compile the neo4j 3.0.1 to be able to use spatial plugin with the **withinDistance** procedure.

**Comment by craigtaverner** [comment]
withinDistance cannot work with 3.0.1, that is the key problem. It needs to be recompiled with 3.0.2 or 3.0.3. That does require a real change to the code to return officially supported types available only in 3.0.2 (org.neo4j.graphdb.spatial.*).

**Comment by craigtaverner** [comment]
OK. I've made a 0.18-neo4j-3.0.3 release to try. Let me know if it works for you.

**Comment by thiagomorato** [comment]
@craigtaverner works like a charm, thank you!

**Comment by JoranBeaufort** [comment]
@craigtaverner I can also confirm that it is working now, great job, thanks!
Using the same pipeline as described above, instead of the error I now get the correct node: 
![fix](https://cloud.githubusercontent.com/assets/13437059/16589763/c795d244-42d4-11e6-8b7f-da9b856dd7cd.png)
Cheers

**Comment by craigtaverner** [comment]
Super! Thanks @thiagomorato and @JoranBeaufort for testing and reporting on this.

**Comment by shahargolan** [comment]
I see the same problem with neo4j 3.1.3
plugins:
  apoc 3.1.3.7
  spatial (0.24) 3.1.1

**Comment by moshebeeri** [comment]
Somehow I get the same issue running 3.3.0 with the relevant spatial plugin.
any idea how to resolve it?
